### ISSUE TITLE
‘ClipboardJS’ is not defined

### ISSUE THREAD

**Issue by Firestar-Reimu** [du33169/gh-proxy-buttons#2]
油猴脚本管理器在第44行报错，应该怎么解决？

**Comment by du33169** [comment]
油猴脚本管理器的语法检查只针对编辑器内的脚本代码，并不会检查使用@require声明的的外部js。ClipboardJS用于点击复制仓库地址，所以如果复制功能正常，可以忽略油猴的报错。
